version: '3.8'

services:
  app:
    build: 
      context: .
      target: base  # Use the base image for development
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL}
      - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
      - BUSINESS_ID=${BUSINESS_ID}
      - MAILER_ADDRESS=${MAILER_ADDRESS}
      - RAPID_KEY=${RAPID_KEY}
    volumes:
      - .:/app  # Mount current directory to /app in container
      - /app/node_modules  # Don't mount node_modules
      - /app/.next  # Don't mount .next
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"  # Changed from 5432:5432 to avoid port conflict
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web-dev-tools
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
